name: Build and deploy ASP.Net Core app to Azure Web App - wvcb-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./backend/WVCB.API

      - name: dotnet publish
        run: |
          dotnet publish -c Release -o ./publish
        working-directory: ./backend/WVCB.API

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./backend/WVCB.API/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_563BD53E4DA647B0AFFDA35CC18DB7FF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DD5D1F3380B6482CA271B80906110905 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC6568A544BC4F8E8F57CCF9DD761032 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "wvcb-api"
          slot-name: "Production"
          package: .
